### ISSUE TITLE
where can I find the paper?

### ISSUE THREAD

**Issue by Dawn-bin** [Waybaba/DIGA#1]

**Comment by zhunzhong07** [comment]
Please send us an email for our CVPR camera-ready version.

**Comment by Waybaba** [comment]
Thank you for your interest in our research. We're pleased to inform you that our paper has been accepted for presentation at the CVPR 2023 conference. Once the conference proceedings are released, the paper will be publicly accessible. We will also ensure to update this repository with the relevant links to the paper as soon as it's available. We appreciate your patience.
