### ISSUE TITLE
versions of pytorch-lighting and hydra

### ISSUE THREAD

**Issue by Solacex** [Waybaba/DIGA#4]
Hello, 

Thanks for your inspiring work! 
When running this code, we found the incompatibility between package hydra and pytroch-lighting. Can you share the version of them, a detailed version of packages would be great!

**Comment by Waybaba** [comment]
Thank you for your kind words and for bringing this compatibility issue to our attention!

We utilize the following versions:

`
    pytorch-lightning==1.8.6
    protobuf==3.20.1
    hydra-core==1.2.0
`

Additionally, we are using Python version 3.7.13.

We have updated the repository to reflect the versions of PyTorch Lightning and Hydra. Please take a moment to check the updates. The Dockerfile should be functioning properly now.

Should you encounter any further issues or have additional questions, please don't hesitate to reach out.

Best regards,
