### ISSUE TITLE
The download method for BDD100K dataset labels.

### ISSUE THREAD

**Issue by y9z9** [Waybaba/DIGA#5]
Hello
1.I couldn't find the download method for the labels of BDD100K dataset. The PNG images for the paths used in the experiment were not included in the Segmentation files downloaded from the official website.
2.I couldn't find any code for aligning classes other than cityscapes in the source code you provided. Could you share more code with me?
Thank you

**Comment by geyanqi** [comment]
Hello, have you addressed this problem?
