### ISSUE TITLE
About IDD dataset

### ISSUE THREAD

**Issue by jdg900** [Waybaba/DIGA#6]
Thank you for sharing your excellent work.

I have a question about the IDD dataset.

You described that you used 100 images as the IDD validation set.

However, the number of samples in the original IDD validation set is 981.

So, could you let me know how you split the 100 images from the IDD validation set?

I'm looking forward to hearing from you.

Thank you.

**Comment by Waybaba** [comment]
Regarding the splitting of the 100 images from the IDD validation set, they were randomly selected. You can refer to the specific implementation details at 

> https://github.com/Waybaba/DIGA/blob/f9fb64e4dd774334ee0930d97af0ae6e80dd206b/src/datamodules/ttda_datamodule.py#L157-L158
Thank you for your insightful question!

Should you have any further questions or require additional clarification, please don't hesitate to ask. I appreciate your interest in our work!

Best regards,

**Comment by Waybaba** [comment]
Regarding the splitting of the 100 images from the IDD validation set, they were randomly selected. You can refer to the specific implementation details at 

> https://github.com/Waybaba/DIGA/blob/f9fb64e4dd774334ee0930d97af0ae6e80dd206b/src/datamodules/ttda_datamodule.py#L157-L158
Thank you for your insightful question!

Should you have any further questions or require additional clarification, please don't hesitate to ask. I appreciate your interest in our work!

Best regards,
